<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="css/style.css">
<title>MultiSéries</title>
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>

<body>

<header>
 <nav id="top">
   <menu> <img src="img/logo.jpg" alt="logo" width="359" height="35" class="logo">
     <ul>
       <li><a href="index.html">Home</a></li>
       <li><a href="series.html">Séries</a></li>
       <li><a href="#">Programação</a></li>
       <li><a href="watchlist.html">Watchlist</a></li>
     </ul>
     <img src="img/option.jpg" alt="" width="33" height="19" style="float: right; margin-top: 9px;">
     <p style="float: right; color: #FFF; margin: 11px 6px 0 0;">Douglas Couto</p>
   </menu>
 </nav>
</header>

<section>

 <nav class="tab">
    <ul>
     <a href="#"><li>Atualizações de Amigos</li></a>
     <a href="#"><li>Atualização Geral</li></a>
	</ul>
 </nav>
 
 <aside id="left">
 </aside>
 
 <section id="right">
 </section>
 
</section>
</body>
</html>